language: python
python:
  - "3.6"
install:
  - pip install -r test_requirements.txt
script:
  - pytest --cov=python --cov=utils --conv=converters test
after_success:
  - coveralls
notifications:
  email: false
