name: CI Build

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Fetch the code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up the Python environment
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt  # Ensure your requirements are listed here

      - name: Run Python Tests with Coverage
        run: |
          pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4  # Send coverage reports to Codecov
        with:
          flags: python  
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  

      # Optional Debug Step
      - name: Debug System Info
        run: |
          uname -a
          python --version
          pip freeze  # List installed packages
