name: CI Build and Test

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Run Python Tests with Coverage
        run: |
          pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml

      - name: Upload Python Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: python
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Step 3: Install C++ build tools and coverage tools
      - name: Install C++ Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ lcov

      # Step 4: Configure and build C++ project with coverage
      - name: Configure and Build C++ Project
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
          make

      # Step 5: Verify build files
      - name: Verify Build Files
        run: |
          cd build
          ls  # Debug: List the contents of the build directory

      # Step 6: Run C++ Tests
      - name: Run C++ Tests
        run: ./build/NNet  # Replace with your actual C++ executable name if needed

      # Step 7: Generate C++ Code Coverage
      - name: Generate Code Coverage Report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info --ignore-errors unused
          lcov --list coverage.info

      # Step 8: Upload C++ Coverage to Codecov
      - name: Upload C++ Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: cpp
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Step 9: Debug Coverage Files (Optional)
      - name: Debug Coverage Files
        run: |
          cd build
          ls -l
          ls -l *.gcda
          cat coverage.info
