name: Run Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Explicitly setting Python 3.10 for compatibility

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev libc-ares-dev libeigen3-dev  # TensorFlow dependencies

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest with coverage
      run: |
        pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml
      env:
        CI: true

    - name: Upload coverage to Coveralls
      run: |
        coveralls

    - name: Debug Step - Check installed packages and system info
      run: |
        pip freeze
        python --version
        uname -a
