name: Multi-Language CI

on:
  push:
    branches:
      - master  # or main if your default branch is main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, julia, cpp]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Python Setup and Tests
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          pip install -r requirements.txt
      - name: Run Python tests
        if: matrix.language == 'python'
        run: |
          pytest --cov=your_python_package

      # Julia Setup and Tests
      - name: Set up Julia
        if: matrix.language == 'julia'
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'  # Use Julia 1.8 (or other versions as required)
      - name: Install Julia dependencies
        if: matrix.language == 'julia'
        run: |
          julia --project=. -e 'import Pkg; Pkg.instantiate()'
      - name: Run Julia tests
        if: matrix.language == 'julia'
        run: |
          julia --project=. -e 'import Pkg; Pkg.test()'

      # C++ Setup and Tests
      - name: Install dependencies for C++
        if: matrix.language == 'cpp'
        run: sudo apt-get install build-essential cmake
      - name: Build and run C++ tests
        if: matrix.language == 'cpp'
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ctest --output-on-failure
