name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.6"]

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r test_requirements.txt

    # Step 4: Run tests with coverage
    - name: Run tests with pytest
      run: |
        python -m pytest --cov=utils --cov=python --cov=converters test

    # Step 5: Upload coverage to Coveralls
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Disable email notifications for GitHub Actions
    - name: Notifications
      run: echo "Email notifications are disabled"
