name: Python CI

# Trigger the workflow on push or pull request events
on: [push, pull_request]

# Define jobs for the workflow
jobs:
  build:
    # Use the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Test across multiple Python versions
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use the latest version

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to use the latest version
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r test_requirements.txt

    # Step 4: Run tests with coverage
    - name: Run tests with pytest
      run: |
        python -m pytest --cov=utils --cov=python --cov=converters test

    # Step 5: Upload coverage to Coveralls
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Disable email notifications
    - name: Notifications
      run: echo "Email notifications are disabled"
