name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Run Python Tests with Coverage
        run: |
          pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml

      - name: Upload Python Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: python
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Step 3: Install C++ build and coverage tools
      - name: Install C++ Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ lcov

      # Step 4: Configure and build C++ project with coverage
      - name: Configure and Build C++ Project with Coverage
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
          make

      # Step 5: Run C++ Tests
      - name: Run C++ Tests
        run: ./build/NNet 

      # Step 6: Generate Coverage Report for C++ Code
      - name: Generate C++ Coverage Report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info --include "*/cpp/*" --ignore-errors unused
          lcov --remove coverage.info '/usr/*' --output-file coverage.info --ignore-errors unused
          lcov --list coverage.info

      # Step 7: Upload C++ Coverage to Codecov
      - name: Upload C++ Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: cpp
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Debugging step 
      - name: Debug Coverage Files
        if: failure()
        run: |
          cd build
          ls -l *.info
          cat coverage.info
