name: Python CI 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python version
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy==1.24.3 pytest pytest-cov coveralls onnx onnxruntime tensorflow==2.14.0
        pip install -r test_requirements.txt

    # Step 4: Run tests with coverage and ensure output to coverage.xml
    - name: Run tests and generate coverage report
      run: |
        pytest --cov=utils --cov=python --cov=converters --cov-report xml:coverage.xml

    # Step 5: Upload coverage to Coveralls
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml
