name: Run Tests and Coverage

on:
  push:
    branches:
      - main  # Run on push to main branch
  pull_request:
    branches:
      - main  # Run on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev libc-ares-dev libeigen3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt  # Ensure this file exists

    - name: Run pytest with coverage
      run: |
        pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml
      env:
        CI: true

    - name: Upload coverage to Coveralls
      run: |
        coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Debug Step - Check installed packages and system info
      run: |
        pip freeze
        python --version
        uname -a
