name: CI - Multi-Language

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Matrix - ${{ matrix.os }} - ${{ matrix.language }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        language: [python, cpp, julia]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Conditional setup based on language
      - name: Set up environment
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Build and Test C++ Code
        if: matrix.language == 'cpp'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake
          cmake . && make && ./your_cpp_tests

      - name: Set up Julia
        if: matrix.language == 'julia'
        uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - name: Build Julia Package
        if: matrix.language == 'julia'
        uses: julia-actions/julia-buildpkg@v1

      - name: Run Julia Tests
        if: matrix.language == 'julia'
        uses: julia-actions/julia-runtest@v1

      - name: Run Python Tests with Coverage
        if: matrix.language == 'python'
        run: |
          pytest --maxfail=5 --disable-warnings --cov=. --cov-report=xml

      - name: Upload Coverage to Codecov
        if: matrix.language == 'python'
        uses: codecov/codecov-action@v4
        with:
          flags: python
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Debug Step for All Languages
      - name: Debug System Info
        run: |
          uname -a
          python --version || true
          gcc --version || true
          julia --version || true
